/*
 * This file was generated by the Gradle 'init' task.
 */

// 1. pluginManagement — ОБЯЗАТЕЛЬНО ПЕРВЫМ
pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}

// 2. dependencyResolutionManagement — для зависимостей проекта
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}

// 3. Проект (без блока plugins, чтобы не было конфликтов)
rootProject.name = "PuTao"
include("app")